export { default as MLogo } from "./MLogo.vue";
export { default as MDiagramIcon } from "./MDiagramIcon.vue";
export { default as MBankIcon } from "./MBankIcon.vue";
export { default as MTargetIcon } from "./MTargetIcon.vue"
export { default as MPieIcon } from "./MPieIcon.vue";
export { default as MPhoneIcon } from "./MPhoneIcon.vue";
export { default as MoneyIcon } from "./MoneyIcon.vue";
export { default as MFinanceAnimeIcon } from "./MFinanceAnimeIcon.vue";
export { default as MTargetAnimeIcon } from "./MTargetAnimeIcon.vue";
export { default as MBudgetAnimeIcon } from "./MBudgetAnimeIcon.vue";
export { default as MSharedAnimeIcon } from "./MSharedAnimeIcon.vue";